#!/bin/sh

#
# Z-Mod E8
#
# Please don't modify this code.
#
# Copyright - Zorge.R - 2010 - motofan.ru
#

####################
# Path block start #
####################
#--|root
	repoz_mypath=${0%/*}
#--|lang
	repoz_lang=$repoz_mypath/lang
#--|content
	repoz_content=$repoz_mypath/content
#--|tmp
	repoz_tmp=$repoz_mypath/rz_tmp
##################
# Path block end #
##################

####################
# Find block start #
####################
# check phone model
rz_model=`cat /etc/modelnum.txt`
# find rokr2 or mgxparser
if [ -f /mmc/movinand1/.zmodstuff/unarc/mgxparser ]; then rz_rokr2="/mmc/movinand1/.zmodstuff/unarc/mgxparser"; else rz_rokr2=`busybox find /usr  -name rokr2`; fi
# find PEP
rz_pep="/ezxlocal/download/mystuff/.system/PEM/PEManager"
# find ZPK
rz_zpk="/ezxlocal/download/mystuff/.zmodstuff/zpk/parse"
# find mpkg/pkg
rz_mpkg="/mmc/mmca1/.system/FsMan/plugins/Installer/Installer"
# find mgs
if [ -f /mmc/movinand1/.zmodstuff/unarc/mgsparser ]; then rz_mgs="/mmc/movinand1/.zmodstuff/unarc/mgsparser"; else rz_rokr2=`busybox find /usr  -name rokr2`; fi
# find imageviewer
imgviewer="/usr/bin/imageviewer"
# find WGET
# for stupid monsterpack (for monsterpack wich haven't wget)
rz_wget="/bin/busybox wget"
# rz_wget="wget"
# find curent server
rz_serv=`cat $repoz_content/reposerv`
# find version
rz_curvers=`cat $repoz_content/repovers`
# find MP model
rz_MPmodel=`cat /ezxlocal/MPmodel`
####################
#  Find block end  #
####################

######################
# NetCONFIG FIX start#
######################
if [ ! -f "$repoz_mypath/netexec.fxd" ]
then
	# удаляем старый netexec.ini
	rm $repoz_mypath/netexec.ini

	# создаем новый конфиг для netexec
	echo -ne "[NetExecConfig]
Command = $repoz_mypath/init" > $repoz_mypath/netexec.ini
	
	# тач
	touch $repoz_mypath/netexec.fxd
fi
######################
# NetCONFIG FIX end#
######################


####################
# Lang block start #
####################
#--|local upd
LANGSTR=`grep '^LanguageType = ' /ezx_user/download/appwrite/setup/ezx_system.cfg | sed 's,^LanguageType = ,,'`
if [ "$LANGSTR" = "" ]
then
	LANGSTR="en-us"
fi
#--|upd lng file
if [ ! -f "${repoz_lang}/rz_${LANGSTR}.txt" ]
then
	. "${repoz_lang}/rz_en-gb.txt"
else
	. "${repoz_lang}/rz_${LANGSTR}.txt"
fi
##################
# Lang block end #
##################

# fix resolv.conf to public DNS
if [ ! -f "/ezxlocal/resolv.conf.bck" ]; then mv /ezxlocal/resolv.conf /ezxlocal/resolv.conf.bck;cp $repoz_mypath/resolv.conf /ezxlocal/resolv.conf;fi

# check - true
. $repoz_content/check_true.sh
